### ISSUE TITLE
Plots not being generated using Make file inside docker

### ISSUE THREAD

**Issue by christopheralex** [UBC-MDS/contraceptive_method_predictor#70]
>Traceback (most recent call last):
  File "/home/contraceptive/src/eda.py", line 75, in <module>
    main(opt["--train_dir"],  opt["--out_dir"])
  File "/home/contraceptive/src/eda.py", line 32, in main
    hist_target.save(out_dir + "/histogram_target.png")
  File "/opt/conda/lib/python3.9/site-packages/altair/vegalite/v4/api.py", line 476, in save
    result = save(**kwds)
  File "/opt/conda/lib/python3.9/site-packages/altair/utils/save.py", line 112, in save
    mimebundle = spec_to_mimebundle(
  File "/opt/conda/lib/python3.9/site-packages/altair/utils/mimebundle.py", line 60, in spec_to_mimebundle
    return altair_saver.render(spec, format, mode=mode, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/altair_saver/_core.py", line 238, in render
    saver = Saver(spec, mode=mode, embed_options=embed_options, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'webdriver'
make: *** [Makefile:18: results/counts_categorical_by_target.png] Error 1

**Comment by harryyikhchan** [comment]
I can run it without any errors occurred. What's your OS and CPU?
